import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    image:"/Image/sweater.webp",
    title:"Men's T shirt",
    categoryName:"clothing",
    orignalPrice:999,
    discountedPrice:499,
    offer:"50%",
    ratings:3.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/jacket.webp",
    title:"Unisex Jacket",
    categoryName:"clothing",
    orignalPrice:1999,
    discountedPrice:1499,
    offer:"25%",
    ratings:4.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/trouser.webp",
    title:"Hiking trouser",
    categoryName:"clothing",
    orignalPrice:1499,
    discountedPrice:1349,
    offer:"10%",
    ratings:4.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/jacket.jpg",
    title:"Womens winter jacket",
    categoryName:"clothing",
    orignalPrice:1999,
    discountedPrice:1499,
    offer:"25%",
    ratings:2.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/backpack3.webp",
    title:"Hiking 20L backpack",
    categoryName:"Backpacks",
    orignalPrice:499,
    discountedPrice:249,
    offer:"50%",
    ratings:2,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/backpack3.webp",
    title:"hiking 50-60L backpack",
    categoryName:"Backpacks",
    orignalPrice:9999,
    discountedPrice:6999,
    offer:"30%",
    ratings:5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/bag.webp",
    title:"10L pocket backpack",
    categoryName:"backpack",
    orignalPrice:199,
    discountedPrice:149,
    offer:"25%",
    ratings:4.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/tent.webp",
    title:"Dome trekking tent 2 person",
    categoryName:"Camping",
    orignalPrice:7999,
    discountedPrice:6499,
    offer:"20%",
    ratings:3.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/tent2.webp",
    title:"Dome trekking tent 3 person",
    categoryName:"camping",
    orignalPrice:9999,
    discountedPrice:8999,
    offer:"10%",
    ratings:4.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/tent3.webp",
    title:"Dome trekking tent 3 person",
    categoryName:"camping",
    orignalPrice:9999,
    discountedPrice:7999,
    offer:"20%",
    ratings:3.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/sweater.webp",
    title:"Men's T shirt",
    categoryName:"clothing",
    orignalPrice:999,
    discountedPrice:499,
    offer:"50%",
    ratings:3.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/shoes.webp",
    title:"trekking shoes MH600",
    categoryName:"footwear",
    orignalPrice:7999,
    discountedPrice:6499,
    offer:"20%",
    ratings:4.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/shoes2.webp",
    title:"trekking shoes MH900",
    categoryName:"footwear",
    orignalPrice:9999,
    discountedPrice:7499,
    offer:"25%",
    ratings:3.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/shoes3.webp",
    title:"trekking shoes XH500",
    categoryName:"footwear",
    orignalPrice:9999,
    discountedPrice:7499,
    offer:"25%",
    ratings:3.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/pole1.webp",
    title:"trekking pole",
    categoryName:"Gears",
    orignalPrice:1499,
    discountedPrice:699,
    offer:"50%",
    ratings:3.5,
    inStock:true,
  },
  {
    _id: uuid(),
    image:"/Image/light.webp",
    title:"Head lamp",
    categoryName:"gears",
    orignalPrice:399,
    discountedPrice:239,
    offer:"20%",
    ratings:3.5,
    inStock:true,
  },
  
]
